backend:
  name: github
  repo: mar-is/gridsome-netlify

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Abstract", name: "abstract", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Content", name: "content", widget: "markdown" }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "authors",
          searchFields: ["name"],
          valueField: name,
          displayFields: ["name"],
        }
      - { label: "Featured Image", "name": "image", widget: "image" }

  - name: "authors"
    label: "Authors"
    folder: "authors"
    create: true
    fields:
      - { label: "Name", name: "fullName", widget: "string" }
      - { label: "Age", name: "age", widget: "string" }
